/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package auction;

import Koneksi.Koneksi;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author nadindradwi
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    Connection con = new Koneksi().konek();
    public Register() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnToLogin = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fullName = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        genderLaki = new javax.swing.JRadioButton();
        genderPerempuan = new javax.swing.JRadioButton();
        telepon = new javax.swing.JTextField();
        tglLahir = new com.toedter.calendar.JDateChooser();
        btnRegister = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 610));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftPanel.setBackground(new java.awt.Color(1, 91, 234));
        leftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Create Your");
        leftPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 320, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Account");
        leftPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 320, -1));

        btnToLogin.setBackground(new java.awt.Color(204, 204, 204));
        btnToLogin.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnToLogin.setText("Login Here");
        btnToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToLoginActionPerformed(evt);
            }
        });
        leftPanel.add(btnToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, -1, 40));

        getContentPane().add(leftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 580));

        rightPanel.setBackground(new java.awt.Color(255, 255, 255));
        rightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setLabelFor(fullName);
        jLabel1.setText("Nama Lengkap");
        rightPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setLabelFor(password);
        jLabel2.setText("Password");
        rightPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setLabelFor(username);
        jLabel3.setText("Username");
        rightPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setLabelFor(alamat);
        jLabel4.setText("Alamat");
        rightPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setLabelFor(telepon);
        jLabel5.setText("Phone Number");
        rightPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Register");
        rightPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setLabelFor(genderLaki);
        jLabel7.setText("Gender");
        rightPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Tanggal Lahir");
        rightPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        fullName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        fullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullNameActionPerformed(evt);
            }
        });
        rightPanel.add(fullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 290, 40));

        username.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        rightPanel.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 290, 40));

        password.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        rightPanel.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 290, 40));

        genderLaki.setBackground(new java.awt.Color(255, 255, 255));
        genderLaki.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        genderLaki.setText("Laki-laki");
        genderLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderLakiActionPerformed(evt);
            }
        });
        rightPanel.add(genderLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, 40));

        genderPerempuan.setBackground(new java.awt.Color(255, 255, 255));
        genderPerempuan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        genderPerempuan.setText("Perempuan");
        genderPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderPerempuanActionPerformed(evt);
            }
        });
        rightPanel.add(genderPerempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, 40));

        telepon.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        rightPanel.add(telepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 290, 40));

        tglLahir.setBackground(new java.awt.Color(255, 255, 255));
        rightPanel.add(tglLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 290, 40));

        btnRegister.setBackground(new java.awt.Color(1, 91, 234));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        rightPanel.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, 90, 40));

        alamat.setColumns(20);
        alamat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        alamat.setLineWrap(true);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        rightPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 290, 60));

        getContentPane().add(rightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 480, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameActionPerformed

    private void genderLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderLakiActionPerformed
        genderPerempuan.setSelected(false);
    }//GEN-LAST:event_genderLakiActionPerformed

    private void btnToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToLoginActionPerformed
        this.dispose();
        Login log = new Login();
        log.show();
    }//GEN-LAST:event_btnToLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
     
        String gender = "";
        
        if(genderLaki.isSelected()){
            gender = "Laki-laki";

        }else if(genderPerempuan.isSelected()){
            gender = "Perempuan";
        }
        
        if(fullName.getText().equals("")
                || username.getText().equals("")
                || password.getText().equals("")
                || gender.equals("") 
                || alamat.getText().equals("")
                || telepon.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "Isi semua form!");
            
        }else {
            
            Date date = tglLahir.getDate();
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            String strDate = formatter.format(date);
            
             try {
                String sql = "INSERT INTO users (nama_lengkap, username, password, gender, tgl_lahir, alamat, no_telepon, role) VALUES(?,?,?,?,?,?,?,?);";
                PreparedStatement ps = (PreparedStatement) con.prepareStatement(sql);
                ps.setString(1, fullName.getText());
                ps.setString(2, username.getText());
                ps.setString(3, password.getText());
                ps.setString(4, gender);
                ps.setString(5, strDate);
                ps.setString(6, alamat.getText());
                ps.setString(7, telepon.getText());
                ps.setString(8, "user");

                ps.executeUpdate();

                JOptionPane.showMessageDialog(null, "Register Berhasil");
                ps.close();
                
                this.dispose();
                Login log = new Login();
                log.show();
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Register Gagal");
                System.out.println(ex);
            } finally {
                 this.refresh();
            }
        }
       
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void genderPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderPerempuanActionPerformed
        genderLaki.setSelected(false);
    }//GEN-LAST:event_genderPerempuanActionPerformed

    public void refresh(){
        fullName.setText("");
        username.setText("");
        password.setText("");
        genderLaki.setSelected(false);
        genderPerempuan.setSelected(false);
        tglLahir.setDate(null);
        alamat.setText("");
        telepon.setText("");
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnToLogin;
    private javax.swing.JTextField fullName;
    private javax.swing.JRadioButton genderLaki;
    private javax.swing.JRadioButton genderPerempuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPasswordField password;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTextField telepon;
    private com.toedter.calendar.JDateChooser tglLahir;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
